### ISSUE TITLE
LBVip is not unbinding

### ISSUE THREAD

**Issue by tabularasa138** [j81blog/GenLeCertForNS#10]
Using the new -UseLbVip function of the script.  It works aside from one little weirdness.  What we are seeing is if the svc_letsencrypt_cert_dummy is left bound to the LBVip (We are using a production LBVip for http to https redirection), in Edge only (which is also super odd), the http to https redirection doesn't work.  Everything works fine in Chrome/Firefox.  Do you tihnk you should add a quick function to unbind that svc_letsencrypt_cert_dummy from the LBVip when it's done doing it's thing?

**Comment by j81blog** [comment]
Can you try to test with the latest [https://github.com/j81blog/GenLeCertForNS/tree/dev](dev) version?

**Comment by tabularasa138** [comment]
This is working now, thank you!
